name: "Terratest"
description: "Run Terratest tests."

runs:
  using: "composite"
  steps:
    - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

    - name: Test with Terratest
      run: |
        # Find and run Terratest tests recursively
        for test_dir in $(find . -type d -name "*_test.go" -exec dirname {} \; | sort -u); do
          echo "Running tests in $test_dir"
          cd $test_dir
          go test -v
          cd -
        done
