name: "Terraform Format Check"
description: "Run Terratest tests."

runs:
  using: "composite"
  steps:
    - name: Terraform Format Check
      run: |
        terraform_files=$(find . -type f -name "*.tf")
        if [ -z "$terraform_files" ]; then
          echo "No Terraform files found."
          exit 0
        fi

        for file in $terraform_files; do
          echo "Formatting $file"
          terraform fmt -check "$file"
        done
